### ISSUE TITLE
보이는 내용 순서가 반대로 되었으면 좋겠다는 이슈가 있었어요. - 용빈TD

### ISSUE THREAD

**Issue by khw7096** [RD101/report#13]

**Comment by baesy0** [comment]
현재 순서는
- gogs 이슈토론 및 로드맵 진행상황 체크
- csi진행상황 공유
- 에셋 라이브러리 툴(dotori)

인데요
반대라고 한다면
- 에셋 라이브러리 툴(dotori)
- csi진행상황 공유
- gogs 이슈토론 및 로드맵 진행상황 체크

이렇게 인가요?

**Comment by khw7096** [comment]
가장 최근 토론된 내용이 맨위에 있는거예요. 노가다로 바꾸어야 하긴 해요. 각 날짜별로..
지금하기에는 너무 양이 많고, 혹시나 나중에 다시 생성한다면 하는것이 나을것 같다고 생각은 되요.

**Comment by baesy0** [comment]
네 그렇습니다.. 지금 하기에는 양이 너무 많습니다.. 다음에 report를 작성해야할 때 고려해보도록 합시당

**Comment by khw7096** [comment]
좋습니다.
